### ISSUE TITLE
Kubernetes performance logs without custom metrics

### ISSUE THREAD

**Issue by kesor** [aws/amazon-cloudwatch-agent#103]
We would like to collect the performance logs from Kubernetes, like Container Insights already does, but to only create the log group and not create custom metrics from these logs. The custom metrics are expensive, and we are not using them.

If only there was an option to allow disabling these custom metrics by making this line conditional ...

https://github.com/aws/amazon-cloudwatch-agent/blob/39d84b8e3f5215a3e6d880b54a88e63a692ecd64/plugins/processors/k8sdecorator/k8sdecorator.go#L56

**Comment by haojhcwa** [comment]
Hi, thank you for your feedback, we are looking into this issue and discussing its feasibility and implementation details, we will update this progress on this issue soon. Thank you for your patience.

**Comment by pingleig** [comment]
(copy from email thread) I think we can add env var to toggle it. We could add it in config but the config translation logic is much harder to implement and we only need a single boolean. As those metrics are required for container insight dashboard,  the default should still be generating EMF log if the env var is not found.

Please let us know if you want to make a PR for that.

**Comment by jaisvar** [comment]
Hi, we have a similar requirement. Is this planned in the roadmap ?

**Comment by pingleig** [comment]
A bit late on this. if you are using ADOT, you should be able to upload log to CloudWatch Logs as non EMF JSON logs and avoid creating CloudWatch Metrics, size of log entry should also decrease as there is no more metadata for metric dimensions https://aws.amazon.com/blogs/containers/container-insights-for-amazon-eks-support-aws-distro-for-opentelemetry-collector/

**Comment by muellerk22** [comment]
Hi @pingleig, I to have been following this request too.
I have read through the documentation and the only exporter I see for CloudWatch Logs is the aws-emf-exporter.  My understanding is this will create the customer metrics.  Maybe i have missed something but I'm still unsure how to collect the metric and send to CloudWatch log without the EMF format.
If you would not mind, can you give a little more detail please?  Thank You.

**Comment by pingleig** [comment]
Copy from https://github.com/aws/containers-roadmap/issues/672#issuecomment-973191514

Yeah, for CW logs and metrics I think EMF Exporter is the only option (might have changed, I haven't work on it for about half a year now...), seems OpenTelemetry collector does not support log yet. But if you are just using CWAgent for ContainerInsights then OTEL Collector works. AWS's distribution of collector is called ADOT https://github.com/aws-observability/aws-otel-collector but all the plugin source are in upstream repo, though they may not be included in the default binary.

I think https://aws-otel.github.io/docs/getting-started/container-insights/eks-infra#configure-metrics-sent-by-cloudwatch-embedded-metric-format-exporter should help, only the metrics you define will be exported in EMF format, otherwise they are just JSON logs (You can still query them using logs insight or create metrics filter). ClouWatch Logs only extract metrics from JSON log automatically if you are using EMF format. 

Actually even in CWAgent we have similar feature on selecting metrics but it only works for Prometheus ...

**Comment by kesor** [comment]
@haojhcwa
> Hi, thank you for your feedback, we are looking into this issue and discussing its feasibility and implementation details, we will update this progress on this issue soon. Thank you for your patience.

It has been more than a year now, any progress updates available?

**Comment by pingleig** [comment]
I remember the decision at that time is not implementing this flag in CloudWatch Agent. I don't think there are further discussion on it.

btw: me and other teammates (e.g. @haojhcwa) who used to work on this repo is now working on other internal projects, so we rarely check github notifications and our information might be outdated.

**Comment by pingleig** [comment]
There is a new blog on using ADOT https://aws.amazon.com/blogs/containers/cost-savings-by-customizing-metrics-sent-by-container-insights-in-amazon-eks/

**Comment by GreasyAvocado** [comment]
@kesor Did you find any solution for this eventually?

**Comment by kesor** [comment]
> @kesor Did you find any solution for this eventually?

I patched a custom version that is working well all this time ; Still waiting for AWS to get their stuff together and actually implement a flag for it ... but after several years of them ignoring, my hopes are not high.

**Comment by BlueIce** [comment]
When researching this topic, I stumbled upon this example config: https://github.com/aws/amazon-cloudwatch-agent/blob/bb8a31b32e43c1488f9635e9c0b2d45e8e1fb375/translator/tocwconfig/sampleConfig/appsignals_and_eks_config.json.

It seems for EKS, custom metric extraction can be disabled via `disable_metric_extraction` flag. I did not find any documentation about this though.

We used it in the advanced configuration of the amazon-cloudwatch-observability EKS add-on in the following way:

```
{
  "agent": {
    "config": {
      "logs": {
        "metrics_collected": {
          "application_signals": {},
          "kubernetes": {
            "disable_metric_extraction": true
          }
        }
      },
      "traces": {
        "traces_collected": {
          "application_signals": {}
        }
      }
    }
  }
}
```
