### ISSUE TITLE
[Feature Request] Support for arm architecture

### ISSUE THREAD

**Issue by jason-riddle** [aws/amazon-cloudwatch-agent#104]
I’d like to run this on my raspberry pi, which is not using arm64, but just arm. Can arm also be a supported platform?

**Comment by hdj630** [comment]
I've put into our feature request queue. But we don't have plan for it right now.

**Comment by haojhcwa** [comment]
Hi, arm32 bit is actually quite diverged and it would be difficult for us to add official support. However, I did a simple test enabling the building specifically for raspberry pi, and you can see my test here: 

https://github.com/haojhcwa/amazon-cloudwatch-agent-1/tree/test-armhf-rpi

You should be able to checkout that branch and build your own agent by `make release`, and you should be able to find the deb package in `build/bin/linux/armhf/`

It does run on my rpi 2, though I only did some basic tests.

**Comment by jason-riddle** [comment]
@haojhcwa Thanks for the explanation. I’m curious, how has arm32 diverged from arm64? I ask because your branch only includes a Makefile change.

**Comment by haojhcwa** [comment]
That's a good question, by diverged, I mean there are many flavors of arm32, I could tweak the make file to build a version of the agent for raspberry pi because its well known and have a rasbian support. However, a general support for arm32 is probably very complicated, for go, there is GOARM variable which supports ARM v5, v6, v7 for 32bit arms, in fact, different version of rpi uses different version of arm, rpi1 uses ARMv6, then rpi2 is ARMv7, and later ones are using 64bit ARMv8.

And for debian packages, a simple search shows there are quite some varieties:

```
$ dpkg-architecture -L |grep arm
uclibc-linux-armel
uclibc-linux-armeb
uclibc-linux-arm
uclibc-linux-arm64
musl-linux-armhf
musl-linux-armeb
musl-linux-arm
musl-linux-arm64
armhf
armel
arm64ilp32
armeb
arm
arm64
....
````

And another main issue for us right now is the difficulty to create automated testing for 32bit arm systems.  

Please let me know if you can build and run the agent using my branch.

**Comment by jason-riddle** [comment]
> However, a general support for arm32 is probably very complicated, for go, there is GOARM variable which supports ARM v5, v6, v7 for 32bit arms, in fact, different version of rpi uses different version of arm, rpi1 uses ARMv6, then rpi2 is ARMv7, and later ones are using 64bit ARMv8.

Yep, I did not realize arm32 was that complicated.

> Please let me know if you can build and run the agent using my branch.

Sure, I'll try it when I get the chance.

**Comment by haojhcwa** [comment]
I've just built it using github actions and created a pre-release so you don't have to build it yourself, you can try download the deb.zip package here: https://github.com/haojhcwa/amazon-cloudwatch-agent-1/releases/tag/v1.247346.1rpi

**Comment by jason-riddle** [comment]
Hey, so I was able to validate that your build works. I don't have a raspberry pi readily configured, so I used `qemu-system-arm` to simulate that device. Happy to provide more info.
