### ISSUE TITLE
Please honor the default AWS credential provider chain 

### ISSUE THREAD

**Issue by castrapel** [aws/amazon-cloudwatch-agent#140]
We're trying to get the AWS Cloudwatch Agent working on an on-prem Windows system (no IMDS) with temporary IAM role credentials. We are having difficulty because Amazon Cloudwatch Agent doesn't fallow the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default).

We have the ability to retrieve temporary 1 hour IAM credentials and refresh them at will. We're using [weep](https://hawkins.gitbook.io/consoleme/weep-cli/aws-credentials-in-the-cli-using-weep), which has the ability to emulate the ECS credential provider. Unfortunately, amazon-cloudwatch-agent doesn't honor the AWS_CONTAINER_CREDENTIALS_FULL_URI environment variable.

We can also emulate the instance metadata service on our system, but in Windows we can't find a way to translate the 169.254.169.254 IMDS address to 127.0.0.1 . We can't point it to a custom metadata IP because this address is hardcoded in amazon-cloudwatch-agent.

We also tried to use the AWS-supported [credential_process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) flow, but amazon-cloudwatch-agent doesn't honor this field.

The other option we're trying is less ideal, it's basically writing credentials to file and refreshing that periodically to keep them fresh on disk.

Is it possible to add a fallback to amazon-cloudwatch-agent so that it abides by the default credential provider chain, like the AWS Go SDK? Or is there a better way to do what we are trying to accomplish?

Thank you!

**Comment by archoversight** [comment]
Doing a drive-by commenting, but would it be possible to setup a loopback address on Windows that contains the IP 169.254.169.254?

**Comment by jhnlsn** [comment]
This issue is a bit stale, but just to close this out you can configure the agent to run on-premise by using credentials file that is created from the `aws configure` command.  Generally they are located in the `~/.aws/` folder on your instance but we enable you to set the credentials file location in the `common-config.toml` file.  You can read more about it here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Agent-commandline-fleet.html

**Comment by mbarneyjr** [comment]
I request that this issue be re-opened, as it's not been solved. It's a best practice to not store credentials on disk in plain text. It's also a best practice to use profiles that refresh credentials for you automatically (via `credential_process`). The use-case I have now is with running the CloudWatch agent on an on-premises server that uses IAM Roles Anywhere for credentials. Ideally we're able to do the following:

```ini
[AmazonCloudWatchAgent]
credential_process = aws_signing_helper ...
region = us-east-1
```

But since the CloudWatch agent behaves differently than AWS SDKs/CLI, we cannot use `credential_process` here and may need something externally that periodically runs `aws_signing_helper` and writes the response to that profile

**Comment by zrfr** [comment]
For those who are still experiencing this: try the RUN_WITH_IRSA environment variable. This is slightly documented here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Observability-EKS-addon.html#install-CloudWatch-Observability-EKS-addon-hybrid
