### ISSUE TITLE
Cloudwatch Agent can start sending the wrong timestamp after arbitrary amount of time

### ISSUE THREAD

**Issue by zsolt-sb** [aws/amazon-cloudwatch-agent#198]
In the screen shot below The columns are the following

  _Timestamp ,  Ingestion Time ,  Message ,  EventID_

Data continued to be posted by the agent to cloudwatch, but the timestamp was stuck at 09:01:25 for several hours.  At midnight UTC, the problem self corrected.  Note, we do not rotate logs at midnight.

If you restart the cloudwatch agent, the timestamp is fixed until it randomly stops changing.  Our current work around is to run a daemon which restarts the cloudwatch agent every 15 minutes to ensure our logs are correctly timestamped in AWS. 

As you can see in the screenshot below, the actual log time and the ingest time all agree.  It is just the reported cloudwatch timestamp that is off.

<img width="1260" alt="Screen Shot 2021-04-10 at 11 32 00 AM" src="https://user-images.githubusercontent.com/47792930/114281981-42ffd880-99f6-11eb-86a2-5d98364e5fda.png">

If there is any way to run this with debugging please let me know and I will gladly provide that information.

Ubuntu 20.04.2 LTS
Linux ip-10-65-53-134 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:56:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent --version
CWAgent/1.247347.5 (go1.15.6; linux; amd64) No Build Date

Source location:
https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

**Comment by mxiamxia** [comment]
Hi @zsolt-sb , Can you please help to provide your `CWAgent logs config`and the full `amazon-cloudwatch-agent.log`? it could be the `timestamp-format` you provided the logs has mismatched the log content in your monitored log files.

**Comment by zsolt-sb** [comment]
Thank you for looking into this.  Here is the Toml file (I added a .txt so I could upload) as well as the cloudwatch-agent.log and configuration-validation.log file.

With respect to the timestamp format, that was an issue I had seen in the past, but with an incorrect format, the logs never got written at all.  In this case, they do get written to AWS.  They just stop correctly time stamping for an unspecified amount of time with no real indication as to why.

[amazon-cloudwatch-agent.log](https://github.com/aws/amazon-cloudwatch-agent/files/6299553/amazon-cloudwatch-agent.log)

[amazon-cloudwatch-agent.toml.txt](https://github.com/aws/amazon-cloudwatch-agent/files/6299556/amazon-cloudwatch-agent.toml.txt)

[configuration-validation.log](https://github.com/aws/amazon-cloudwatch-agent/files/6299559/configuration-validation.log)

**Comment by kyoicito** [comment]
Hi @zsolt-sb, sorry for jump in.

I don't know which one is the log file you have encountered the issue, but I found all of three log files must have been set to the same `timestamp_format` according to your `amazon-cloudwatch-agent.toml.txt`.

```
      timestamp_layout = "Jan 02 15:04:05"
      timestamp_regex = "(\\w{3} \\d{2} \\d{2}:\\d{2}:\\d{2})"
```

This layout and regex implies your `timestamp_format` setting in agent config is like below as [1] shows.

```
"timestamp_format": "%b %d %H:%M:%S"
```

The symbol `%d` stands for "Day of the month as a **zero-padded** decimal number" [2].

Your actual timestamp format in your log is, however, **NOT** zero-padded from the screenshot like below.

```
Apr 9 23:59:52
```

CloudWatch Agent reuses the last valid timestamp which have been most recently matched with `timestamp_format` if it can't find timestamp which matches `timestamp_format` in the log message [3].

From your timestamp "2021-04-09T09:01:25.000-07:00", I assume that a log event might exist which message includes "Apr 09 16:01:25" before.

The agent might reuse this timestamp until the log event which message starts with "Apr 10 00:00:04", then after that the agent recognize the timestamp correctly, the following log events have the correct timestamps.

I believe this issue is caused by your `timestamp_format` which has mismatched the log content in your monitored log files as @mxiamxia says.
Please review your JSON config and if `%d` is used in `timestamp_format` for this log file, please change it to `%-d` (symbol for not zero-padded day) and then reload the config and restart the agent with `-a fetch-config -s -c` option [4] unless you have been using multiple config files for the agent [5].

#### References:
[1] https://github.com/aws/amazon-cloudwatch-agent/blob/master/translator/translate/logs/logs_collected/files/collect_list/ruleTimestampFormat.go

[2] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-Configuration-File-Details.html#CloudWatch-Agent-Configuration-File-Logssection

[3] https://github.com/aws/amazon-cloudwatch-agent/blob/c7a6db50292d742b1c2688a3a841e3643669521c/plugins/outputs/cloudwatchlogs/pusher.go#L349-L361

[4] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Agent-commandline-fleet.html#start-CloudWatch-Agent-EC2-commands-fleet

[5] https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-common-scenarios.html#CloudWatch-Agent-multiple-config-files

**Comment by zsolt-sb** [comment]
@kyoicito  I wanted to thank you.  Your advice was spot on.  Upon fixing the pattern to match the leading space format vs leading zero, the issue did not rear its head and being June 1st, I would have expected to see the problem happen today.   Thank you all for you meaningful help.
