### ISSUE TITLE
Missing Windows Event logs in CloudWatch Logs `windows_events` plugin

### ISSUE THREAD

**Issue by mxiamxia** [aws/amazon-cloudwatch-agent#199]
### Description
This is a known issue when uploading Windows Event Logs to CloudWatch by using `windows_events` in CloueWatch Agent. Some of Windows Events will be failed to send  in the following condition.

When an operation is performed in Windows OS. A bunch of event logs will appear in `Event Viewer` with `Timestamp`, `event ID`, `Source service`.  For example,  Chrome application update events could have several related source service registered, (e.g. gupdate, gupdatem). If any of them is not registered itself correctly, it will block the whole event logs being retrieved from CWAgent and upload to CloudWatch.

**Comment by adam-mateen** [comment]
I reproduced the issue on Windows Server 2019 (EC2 instance).
I ran this PowerShell script:
```
$ename = "Application"
$src = "Hermy"
$msg = "Hello World! "

if ([System.Diagnostics.EventLog]::SourceExists($src) -eq $False) {
	New-EventLog -LogName $ename -Source $src
}

$i = 0
while (1) {
	$cur_msg = $msg + "$i"
	write-output $cur_msg
	Write-EventLog -LogName $ename -Source $src -EventID 3001 -EntryType Error -Message $cur_msg
	sleep(1)
	$i += 1
}
```
Which outputs a new ERROR level event every second.
While that was running I installed Chrome, uninstalled Chrome, repeat.
I looked at CloudWatch console and I saw a dropped event.
I expected to see a messages like:
```
Hello World! 1
Hello World! 2
Hello World! 3
Hello World! 4
Hello World! 5
```
Instead 1 of the events was not reported.

The issue is that events may be retrieved in a batch.
And if the Agent encounters an issue with any of the events in the batch, it drops the whole batch.
Refer to `getRecords()`:
https://github.com/aws/amazon-cloudwatch-agent/blob/c3894b985db74b51a8dc07f087e1a2da698dff2b/plugins/inputs/windows_event_log/wineventlog/wineventlog.go#L327

I will open a PR to continue processing the batch of events even when 1 or more events cannot be rendered.
