### ISSUE TITLE
ruleTimestampFormat.go %f processing...

### ISSUE THREAD

**Issue by marcb** [aws/amazon-cloudwatch-agent#245]
I think there is a bug in the way '**`%f`**' is handled in [ruleTimestampFormat.go](https://github.com/aws/amazon-cloudwatch-agent/blob/109558506e405c50472a4b6b0fb4f514f8bd8c0e/translator/translate/logs/logs_collected/files/collect_list/ruleTimestampFormat.go)

[line 75](https://github.com/aws/amazon-cloudwatch-agent/blob/109558506e405c50472a4b6b0fb4f514f8bd8c0e/translator/translate/logs/logs_collected/files/collect_list/ruleTimestampFormat.go#L75) 
```
	"%f":  ".000",
```

[line 99](https://github.com/aws/amazon-cloudwatch-agent/blob/109558506e405c50472a4b6b0fb4f514f8bd8c0e/translator/translate/logs/logs_collected/files/collect_list/ruleTimestampFormat.go#L99):
```
	"%f":  "(\\d{1,9})",
```

should be aligned around `%f` being numeric.

That is line 75 should be
```
	"%f":  "000",
```

That way in _amazon-cloudwatch-agent.json_ the following

```
            "timestamp_format": "\"%Y-%m-%dT%H:%M:%S.%fZ\"",
```

would no longer turn into the following in _amazon-cloudwatch-agent.toml_

```
      timestamp_layout = "\"2006-01-02T15:04:05..000Z\""
      timestamp_regex = "(\"\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.(\\d{1,9})Z\")"

```
but rather

```
      timestamp_layout = "\"2006-01-02T15:04:05.000Z\""
      timestamp_regex = "(\"\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.(\\d{1,9})Z\")"
```

**Comment by mxiamxia** [comment]
`timestamp_regex` will supersedes `timestamp_layout` for `timestamp_format` field so it shouldn't cause the problem on timestamp matching in the real case. We'll double check the changes for `"%f":  ".000",` . Thank you.

**Comment by jhnlsn** [comment]
%f is `Fractional seconds as a decimal number (1-9 digits), zero-padded on the left.`, implying that it will be a a decimal representation of fractional seconds, which includes the decimal.  In your example there is no need to include the `dot` in front of the `%f`, just remote the `.` value between `%S` and `%f`

**Comment by brwebb** [comment]
I ran into this same issue.

CWAGENT_VERSION = 1.247355.0b252062

The entries in my log file are JSON. The timestamp is embedded in the like. An example looks like `"time":"2022-10-03T22:15:18.405Z",`

In the cloudwatch agent config I have `"timestamp_format": "%Y-%m-%dT%H:%M:%S.%fZ"`

When the logs are parsed and loaded into CloudWatch the `@timestamp` values are incorrect. For example, a `time` value of `2022-10-03T22:15:18.405Z` will be seen as a `@timestamp` value of `1664835319030`, which corresponds to `2022-10-03T22:15:19.030Z`.

I then test removing the "Z" from the timestamp_format and this fixed the problem. The `@timestamp` values in CloudWatch properly matched the `time` JSON values in the log file.

I suspect there is some bug that is triggered when 

1. there is a string suffix after `%f` and
2. the subsecond value is in milliseconds and not microseconds. 

I also noticed the same issue listed above where the `timestamp_layout` seems to have an extra period. I suspect that is not directly related to the bug I observed since I was able to get the parsing working by removing the "Z".

I expected the parsing to work with the original config `"timestamp_format": "%Y-%m-%dT%H:%M:%S.%fZ"`
