### ISSUE TITLE
Question/Feature request: Append new metrics to mem, measurement

### ISSUE THREAD

**Issue by GlennChia** [aws/amazon-cloudwatch-agent#299]
# Description

`configure (append)` does not work for the `measurement` attribute of `mem`. In this case, I am attempting to append a string to a list. There are similar issues reported regarding this. I have added links to them at the bottom of this issue. Thanks in advance for helping to look into this question/feature request!

# Details

Use ssm to configure the cloudwatch agent using `AmazonCloudWatch-ManageAgent`

1. Use `configure` to configure some baseline from a parameter in the SSM parameter store. This works :
```json
{
  "agent": {
    "metrics_collection_interval": 60,
    "run_as_user": "cwagent"
  },
  "metrics": {
    "append_dimensions": {
      "AutoScalingGroupName": "${aws:AutoScalingGroupName}",
      "ImageId": "${aws:ImageId}",
      "InstanceId": "${aws:InstanceId}",
      "InstanceType": "${aws:InstanceType}"
    },
    "metrics_collected": {
      "mem": {
        "measurement": [
          "mem_used_percent"
        ],
        "metrics_collection_interval": 60
      }
    }
  }
}
```
2.  Then with another JSON configuration stored in the SSM Parameter Store, use `configure (append)` to attempt to append it. This does not work:

```json
{
  "metrics": {
    "metrics_collected": {
      "mem": {
        "measurement": [
          "mem_free"
        ]
      }
    }
  }
}
```
3. I also tried adding the `metrics_collection_interval` but that didn't work as well
```json
{
  "metrics": {
    "metrics_collected": {
      "mem": {
        "measurement": [
          "mem_free"
        ],
        "metrics_collection_interval": 60
      }
    }
  }
}
```
# Error log

The error is

```
2021/10/22 11:45:55 Failed to merge multiple json config files.

2021/10/22 11:45:55 Under path : /metrics/metrics_collected/mem | Error : Different values are specified for mem

2021/10/22 11:45:55 Configuration validation first phase failed. Agent version: 1.0. Verify the JSON input is only using features supported by this version.

failed to run commands: exit status 1
```

# Similar issues

#133 mentions appending procstat to config, where objects are appended to a list
#238 cites several limitations and gotchas of the `configure (append)`, one of them being `Extending/adding to a measurement` which is the same issue faced here. However, it phrases it as a documentation update. Could this be a possible feature request instead? Not too sure if it's possible.

Thanks in advance for your help!

**Comment by Rawlusdivision** [comment]
Please re-open investigation, additional findings observed for root cause and corrective action.

- Encountered a similar issue when modifying the 'metrics_collection_interval' from "30" to either 180sec or 300secs and updating EC2/SSM via RunCommand.


------------------------------------------------------------------------------------------------
metrics_collection_interval 
------------------------------------------------------------------------------------------------
{"logs":null,"metrics":{"append_dimensions":{"InstanceId":"${aws:InstanceId}"},"metrics_collected":{"disk":{"measurement":[{"name":"used_percent","unit":"Percent"}],"metrics_collection_interval":30,"resources":["*"],"append_dimensions":{"ClusterName":"credcore-test"}},"mem":{"measurement":[{"name":"used_percent","unit":"Percent"}],"metrics_collection_interval":30,"resources":["*"],"append_dimensions":{"ClusterName":"credcore-test"}}},"aggregation_dimensions":[["ClusterName"]]}}
------------------------------------------------------------------------------------------------


- Next, the following error occurred  whereby, it Failed to merge multiple json config files. 
- To workaround the issue, the below [JSON] and [TMP] files needed to be removed. Followed, by RE-RUNNING the SSM parameterStore update via SSM RunCommand procedures for mitigation.


---------------
- path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
---------------
- path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/ssm_AmazonCloudWatch-ApplicationInsights-SSMParameterForApplicationInsightsContainerInsightsEKSCLUSTERcredcoretestEKSCLUSTERcredcoretest.tmp
---------------


------------------------------------------------------------------------------------------------
SSM-ParameterStore-Error-Description-Details
------------------------------------------------------------------------------------------------
2023/12/22 06:19:40 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json ...
2023/12/22 06:19:40 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/ssm_AmazonCloudWatch-ApplicationInsights-SSMParameterForApplicationInsightsContainerInsightsEKSCLUSTERcredcoretestEKSCLUSTERcredcoretest ...
2023/12/22 06:19:40 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/ssm_AmazonCloudWatch-ApplicationInsights-SSMParameterForApplicationInsightsContainerInsightsEKSCLUSTERcredcoretestEKSCLUSTERcredcoretest.tmp ...
2023/12/22 06:19:40 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/ssm_AmazonCloudWatch-ApplicationInsights-SSMParameterForEKSCLUSTERcredcoretest ...
2023/12/22 06:19:40 Failed to merge multiple json config files.
2023/12/22 06:19:40 Failed to merge multiple json config files.
2023/12/22 06:19:40 Under path : /metrics/metrics_collected/mem | Error : Different values are specified for mem
2023/12/22 06:19:40 Configuration validation first phase failed. Agent version: 1.0. Verify the JSON input is only using features supported by this version.
failed to run commands: exit status 1
------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------
AWS Resource Versions | Configuration Items
------------------------------------------------------------------------------------------------
CloudWatch-Agent version: 1.300032.2b361
Kernel: Linux version 5.10.178-162.673.amzn2.x86_64
ENA driver version: 2.8.3g
SSM agent version: 3.1.1732.0
Cloud-Init version: 19.3-46.amzn2
EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.26.2, containerd: 1.6.*) 
------------------------------------------------------------------------------------------------

**Comment by massimocode** [comment]
@GlennChia  I just had this same issue. I tried to update the monitoring interval and the service just wouldn't boot after that. In the end I had to uninstall and wipe all traces of it from the system before I could successfully reinstall and get it working again, with the new config this time.
