### ISSUE TITLE
Missing Logs With Python Rotating File Handler And Minimal Log Messages

### ISSUE THREAD

**Issue by akozd** [aws/amazon-cloudwatch-agent#447]
There is potential for logs to go missing and to have partial logging messages when using a rotating file handler within an application that produces very few logs. 

The behavior seems to be when a log file is rotated (ex: `logfile.log` is renamed to `logfile.log.2022-04-18`) and a new message is written to `logfile.log`, if the byte length of the single new message is >= the byte length of the entire old log file, then the new message will be entirely missing or partially missing.

We are using the latest version of the CloudWatch Agent, no code modifications have been made, and there is nothing unusual about our environment.

We are mitigating this issue currently just by decreasing the rate at which log files get rotated.  

Minimal reproducible example:

CloudWatch agent `config.json`:
```json
{
    "agent": {
      "run_as_user": "root",
      "credentials": {
        "role_arn": "arn:aws:iam::------------:role/EC2AdminRole"
      }
    },
    "logs": {
      "logs_collected": {
        "files": {
          "collect_list": [
            {
              "file_path": "/home/ec2-user/amazon-cloudwatch-agent/logdest/logs.log*",
              "log_group_name": "custom-agent-logs",
              "log_stream_name": "{instance_id}"
            }
          ]
        }
      }
    }
  }
  
```
`log_generator.py`:
```python
import glob
import os
import logging
from logging.handlers import TimedRotatingFileHandler
import time
import json

# get root logger
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# rotate our log file every 3 minutes
handler = TimedRotatingFileHandler("logdest/logs.log", when="M", interval=3)
logger.addHandler(handler)

# log a message
logging.info(json.dumps({"Metric": "12345"*10}))
# sleep for 4 minutes so that file will rotate upon next log message
time.sleep(60*4)
# log another message (this one will not appear since byte length of message == byte length of old log file)
logging.info(json.dumps({"Metric": "09876"*10}))
# sleep for another 4 minutes so that file will rotate upon next log message
time.sleep(60*4)
# this message will be partially written
logging.info({"Metric": "1234567890"*10})
```

CloudWatch Logs:
*Notice that the second log message is entirely missing, and that the third message is missing its first 65 bytes.*
| Timestamp | Message | Bytes |
| - | - | - |
2022-04-18T11:04:49.539-04:00|{"Metric": "12345123451234512345123451234512345123451234512345"}|64
2022-04-18T11:13:21.539-04:00|45678901234567890123456789012345678901234567890'}|49

Log Files on EC2:
`logs.log` (114 bytes):
```
{'Metric': '1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890'}
```
`logs.log.2022-04-18_15-09` (64 bytes):
```
{"Metric": "09876098760987609876098760987609876098760987609876"}
```
`logs.log.2022-04-18_15-05` (64 bytes):
```
{"Metric": "12345123451234512345123451234512345123451234512345"}
```

**Comment by SaxyPandaBear** [comment]
Thanks for the very succinct repro case. I just reproduced the issue on my own. I'll take a look at this

**Comment by SaxyPandaBear** [comment]
At this point, it seems to me like there are two potential bugs related to log rotation:
1. Your specific scenario where that second log in your repro case gets dropped because the size of the log == the agent state file offset
2. The partial message that only publishes the end of the log line after the offset.

**Comment by SaxyPandaBear** [comment]
I still want to investigate this a little further, but I think I found the root cause. 

### Analyzing repro case logs
Looking at a snippet of the original repro case logs:
```
2022-04-19T14:15:00Z W! [inputs.tail] Stopping tail as file no longer exists: /home/ec2-user/logs.log
2022-04-19T14:15:00Z I! [logagent] Log src has stopped for custom-agent-logs/i-0e3adad213edfd7b5(/home/ec2-user/logs.log)
2022-04-19T14:15:00Z I! [inputs.logfile] Reading from offset 65 in /home/ec2-user/logs.log
2022-04-19T14:15:00Z I! [logagent] piping log from custom-agent-logs/i-0e3adad213edfd7b5(/home/ec2-user/logs.log) to cloudwatchlogs with retention 14
```
What happens here is:

| Log | Explanation |
|-----|-------------|
| `Stopping tail as file no longer exists: /home/ec2-user/logs.log` | The log file gets rotated*  |
| `Log src has stopped for custom-agent-logs/i-0e3adad213edfd7b5(/home/ec2-user/logs.log)` | The tailing goroutine for the log file is killed/cleaned up |
| `Reading from offset 65 in /home/ec2-user/logs.log` | The agent reads the state file for this log, to figure out where to seek in the file and continue monitoring |
| `piping log from custom-agent-logs/i-0e3adad213edfd7b5` | The agent starts reading from the log file again** |

`*` - One thing that tripped me up for a while was that in the repro case, even though the logger is configured to rotate every 3 minutes, the rotation doesn't actually occur until the next log line gets emitted:
```
-rw-rw-r-- 1 ec2-user ec2-user      115 Apr 19 22:02 logs.log
-rw-rw-r-- 1 ec2-user ec2-user     3900 Apr 19 20:39 logs.log.2022-04-19_20-38
-rw-rw-r-- 1 ec2-user ec2-user     3900 Apr 19 20:40 logs.log.2022-04-19_20-40
-rw-rw-r-- 1 ec2-user ec2-user       65 Apr 19 21:54 logs.log.2022-04-19_21-54
-rw-rw-r-- 1 ec2-user ec2-user       65 Apr 19 21:58 logs.log.2022-04-19_21-58
```
I assume this is just how the logger works under the hood. Not _super_ important overall, but something that confused me for a while until I finally looked at the modified time for the files. 
`**` - will get into this deeper, but essentially, the agent does not gracefully handle the log rotation in this scenario and relies on something else to pick up the file again after the previous routine gets killed

### Analyzing altered case logs
This is to answer two questions about the altered scenario:
1. Why did the second message get published in this scenario?
2. Why did the third message still get truncated?

Looking at the logs - this is from the 2nd message of the test:
```
2022-04-19T16:23:03Z W! [inputs.tail] Stopping tail as file no longer exists: /home/ec2-user/logs.log
2022-04-19T16:23:03Z I! [logagent] Log src has stopped for custom-agent-logs/i-0e3adad213edfd7b5(/home/ec2-user/logs.log)
2022-04-19T16:23:04Z I! [inputs.logfile] Reading from offset 65 in /home/ec2-user/logs.log
2022-04-19T16:23:04Z I! [logagent] piping log from custom-agent-logs/i-0e3adad213edfd7b5(/home/ec2-user/logs.log) to cloudwatchlogs with retention 14
2022-04-19T16:23:05Z I! [inputs.tail] Re-opening truncated file /home/ec2-user/logs.log ...
```

This is mostly the same, however there is one additional log line: 
```
Re-opening truncated file /home/ec2-user/logs.log ...
```
What happened here in my altered test scenario was I modified the second log to emit a log message < the size of the first one. The agent determined based on this that the file was truncated at some point **completely separate from the actual log rotation that happened**, so it started reading the file **from the beginning**, hence why even though there was a log that said it would start at offset 65, it still consumed the log line that was < 64 bytes. 

Then as noted from the CloudWatch Logs output from the second test, the third message still only partially gets uploaded to CloudWatch, though a larger portion of it than previously. This is due to the fact that the agent did not determine/know that the log file got rotated, so it started reading from offset 55, and consumed part of the third log message as new log content (skipping the first 55 bytes). 

---
### **
In this scenario, we don't want the agent to start from an offset. The file got rotated, which means that the file got truncated at some point and as illustrated by this repro case, the agent can miss logs. 

I was digging through the code and found this `ReOpen` boolean flag, which originates from the forked telegraf tail plugin and isn't exposed as a configuration in the CloudWatch agent:

https://github.com/aws/amazon-cloudwatch-agent/blob/6bc4507351628262a27e582f486c3aa6db1c7c26/plugins/inputs/logfile/logfile.go#L191

Then in the tail plugin, it looks uses this flag to determine whether to reopen a file or to stop:
https://github.com/aws/amazon-cloudwatch-agent/blob/6bc4507351628262a27e582f486c3aa6db1c7c26/plugins/inputs/logfile/tail/tail.go#L442-L455

Looking at the original repro case, this `Stopping tail` log is the first log line that shows up after a rotation occurs. 

What happens here is that when the rotation occurs, this function returns an error, which ultimately closes the file monitor. **As far as I can tell, this does not cleanly restart tailing the file.** It determines that external log rotation as a reason to stop monitoring the file. 

> But then what is causing the file to be read from again? 

The main agent has a long running process for picking up log files. This is mostly important in the scenario where someone would configure a log file path with wildcards in it, in order to pick up new files regularly:
https://github.com/aws/amazon-cloudwatch-agent/blob/6bc4507351628262a27e582f486c3aa6db1c7c26/logs/logs.go#L93-L116

So the reason why the agent is able to semi-gracefully handle killing the original tail routine when the file gets truncated is because this separate routine will rediscover that log file and start tailing it again, reading the offset as usual. 

This is **not** how we want it to behave in this scenario though. What we want is to reopen the file and start from the beginning again. 

I cut a branch, flipped the `ReOpen` flag to `true`, and that one-line code change resolves the repro case. I was able to publish all 3 logs, in full, with that change.

My biggest concern is that this is definitely a change in behavior - though it could be a change in behavior that fixes a longstanding bug that has gone unnoticed. 

As a simple sanity test, I ran another simple test where I wrote N logs, one log line per second, and had the logger rotate the file after 1 minute to verify that it handled that case, which it did. But I want to do some more testing with that change because it feels too obvious/minor of a change to be such an impactful fix.

**Comment by akozd** [comment]
Thank you for the excellent deep dive. I agree that the `ReOpen` flag should be set to `true` in the case for rotating logs. I see that when `true`, this flag will mimic the `tail -F` command in Linux:

https://github.com/aws/amazon-cloudwatch-agent/blob/6bc4507351628262a27e582f486c3aa6db1c7c26/plugins/inputs/logfile/tail/tail.go#L54

Which will handle reopening the log file after it is rotated. [Good stack exchange post](https://unix.stackexchange.com/a/291935). 

Hopefully this really is a simple one-line fix...

**Comment by SaxyPandaBear** [comment]
Also confirmed that the same bug appears on Windows:
```
{     "Metric": "12345123451234512345123451234512345123451234512345" }
--
5678901234567890123456789012345678901234567890'}
```
Is what gets published to CWL. Now, one interesting thing I saw is that I think that Windows adds an extra byte hidden in there.

The log line I see in the agent log file on Windows indicates that the offset is 1 byte farther along than on Linux. Ultimately, got the same result so not too important to drill down on where that extra byte comes from, but just thought it was interesting.
```
2022-04-20T20:25:07Z I! [inputs.logfile] Reading from offset 66 in C:\Users\Administrator\Desktop\logs.log
```

---
This morning I set up two Linux boxes, one with my fixed version and one with the latest release and started publishing logs to them continually just to make sure there wasn't some obvious regression. I'll work on setting something up on two Windows machines and then once I see everything looks normal, I'll work on publishing a PR for this fix.

**Comment by SaxyPandaBear** [comment]
Still been looking into this. Although flipping that ReOpen flag does alleviate it for this scenario, I realized that this test indicates that what you reproduced was expected behavior https://github.com/aws/amazon-cloudwatch-agent/blob/8eb0d143ac958902c67dd442bfbf606781116d07/plugins/inputs/logfile/logfile_test.go#L717-L721

The above test explicitly validates that recreating the log file with the same name starts from the saved offset. Need to figure out _why_ this behavior was made by design, since it seems counterintuitive to me.
