### ISSUE TITLE
ctl script should handle "onPrem" as well as "onPremise"

### ISSUE THREAD

**Issue by SaxyPandaBear** [aws/amazon-cloudwatch-agent#474]
**Describe the bug**
Changing to use `onPremise` is a breaking change introduced in #417. The agent should accept the existing `onPrem` flag as well.

**Comment by khanhntd** [comment]
Personally, I would not prefer to add `onPrem` flag even though its breaking existing user's behavior because considering the scale of  `custom flag`, we should reduce addition customer flags whenever its possible. However, this change indeed could break internal customer impacts after `merging from live`; but, I would say a more addressing-problem would be the breaking change's visibility regarding external and internal customer.

**Comment by khanhntd** [comment]
I would disagree with that. Because we expect customers to not run the translator themselves; therefore, we should change the internal flow as smooth as possible. Such as the mentioned PR, why it should change mode from `onPremise` to `onPrem` only to adapt the translator and the downloader? Does every time we make a new `custom flag`, we should change the internal components as well or is this an exception? I would prefer more consistent flag between these components; and I would also say its because the existing customer's behavior does not mean its good though.

**Comment by SaxyPandaBear** [comment]
> same as DockerShim drawback for maintainability

It's **not** the same though. Kubernetes announced that they were deprecating Dockershim support in k8s in a blog on December 2, 2020. https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

They gave almost 1.5 years since the announcement in 2020 until the v1.24 release of k8s which actually removes the Docker support. https://kubernetes.io/releases/#release-v1-24

What we did was completely pull out the old flag without any announcement or transition period. This is bad user experience all across the board and is not an acceptable way to introduce a breaking change.

**Comment by SaxyPandaBear** [comment]
Done as part of #543
