### ISSUE TITLE
Add common rules to ignore_fs for input.disks plugin

### ISSUE THREAD

**Issue by lifeofguenter** [aws/amazon-cloudwatch-agent#613]
Logs are being spammed with:

```
E! [inputs.disk] [SystemPS] => error getting disk usage ("/sys/kernel/debug/tracing"): permission denied
```

At a minimum the cloudwatch-agent should add the following config by default:

```
ignore_fs = ["tracefs"]
```

but more might be even better as these are not typical disks you want/need to monitor.

Reference in upstream: https://github.com/influxdata/telegraf/issues/10897

**Comment by adam-mateen** [comment]
Agreed. It looks like 2 different approaches were taken in Telegraf:
1. Change the log level to debug - https://github.com/influxdata/telegraf/pull/10925/files
2. Added a new option `"ignore_mount_opts"`- https://github.com/influxdata/telegraf/pull/11039/files

CloudWatch Agent already has the `"ignore_file_system_types"` option in the JSON config. Which translates into the `"ignore_fs"` option in TOML config. There are no defaults right now.

We could change the JSON translation so that if no `"ignore_file_system_types"` option is given it will translate to, `ignore_fs = ["tracefs"]`, but that would change the behavior for a lot of existing users. So probably not a good idea...

Instead we can change the config wizard so by default JSON configs are created with  `"ignore_file_system_types"`.
Does that sound good? Any other ideas?

**Comment by adiroiban** [comment]
Hi. Any luck in adding support for ingore_fs in cloudwatch ?

Thanks
