### ISSUE TITLE
[Feature Request] AutoScalingGroupName variable option for log_group_name / log_stream_name in Logs section

### ISSUE THREAD

**Issue by mengmann** [aws/amazon-cloudwatch-agent#738]
**Is your feature request related to a problem? Please describe.**
Currently there is no way use the instances AutoScalingGroupName as a variable either for `log_group_name` nor for `log_stream_name` configuration.

**Describe the solution you'd like**
... to have AutoScalingGroupName as variable to use it like this:
```json
{
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/nginx/access.log",
            "log_group_name": "{autoscaling_group_name}",
            "log_stream_name": "/var/log/nginx/access.log",
            "timestamp_format": "[%a/%b/%Y:%H:%M:%S %z]",
            "timezone": "Local",
            "retention_in_days": 30
          },
          {
            "file_path": "/var/log/nginx/error.log",
            "log_group_name": "{autoscaling_group_name}",
            "log_stream_name": "/var/log/nginx/error.log",
            "timestamp_format": "%Y/%m/%d %H:%M:%S",
            "timezone": "Local",
            "retention_in_days": 30
          }
        ]
      }
    }
  }
}
```

**Describe alternatives you've considered**
Maybe it would be a good generic approach to make use of instance tags (needs sufficient IAM permission). But so we can basically add any tag key as a aggregation key for Cloudwatch Logs.
example: {tag:key}
```
"log_group_name": "{tag:aws:autoscaling:groupName}",
```

**Additional context**
Currently the list of available variables is limited to this: {instance_id}, {hostname}, {local_hostname}, and {ip_address}
In the metrics section one can use the following variables for dimensional metric aggregation:  ${aws:ImageId},  ${aws:InstanceId}, ${aws:InstanceType}  and already ${aws:AutoScalingGroupName}

So maybe there is some room for unification / consistency improvements here?

**Comment by SaxyPandaBear** [comment]
> Maybe it would be a good generic approach to make use of instance tags

This was my first thought, because doing something outside of those bounds can become kind of invasive, permission-wise. We get this information via IMDS from the running host. That doesn't directly expose the AutoScalingGroup name. It is simpler for us to just read from tags (and gives a wider benefit for other customers who want tag based labeling). 

If we tried to avoid using instance tags, we would have to do some lookup from the InstanceID or something to figure out the auto scaling group (which probably would end up looking at tags anyway in the simplest form). 

> So maybe there is some room for unification / consistency improvements here?

I personally agree. Part of me wonders if the `aws:` prefix is to delineate placeholders that use IMDS from other host-specific values like the hostname.
